//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSControlSMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSControlSMS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Acc Alarm.
        /// </summary>
        internal static string AccAlarmOff {
            get {
                return ResourceManager.GetString("AccAlarmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Acc Alarm.
        /// </summary>
        internal static string AccAlarmOn {
            get {
                return ResourceManager.GetString("AccAlarmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off Engine.
        /// </summary>
        internal static string AccOff {
            get {
                return ResourceManager.GetString("AccOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On Engine.
        /// </summary>
        internal static string AccOn {
            get {
                return ResourceManager.GetString("AccOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple app for sending SMS commands to GPS trackers..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been reset to default values..
        /// </summary>
        internal static string AppReset {
            get {
                return ResourceManager.GetString("AppReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast. Reliable. Easy..
        /// </summary>
        internal static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart the device to factory settings?.
        /// </summary>
        internal static string ConfirmFactory {
            get {
                return ResourceManager.GetString("ConfirmFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the unit name.
        /// </summary>
        internal static string EmptyUnit {
            get {
                return ResourceManager.GetString("EmptyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name already exists..
        /// </summary>
        internal static string ExistingUnit {
            get {
                return ResourceManager.GetString("ExistingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Power Alarm.
        /// </summary>
        internal static string ExtPowerAlarmOff {
            get {
                return ResourceManager.GetString("ExtPowerAlarmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Power Alarm.
        /// </summary>
        internal static string ExtPowerAlarmOn {
            get {
                return ResourceManager.GetString("ExtPowerAlarmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Factory Settings.
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string GoogleLink {
            get {
                return ResourceManager.GetString("GoogleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MessageLabel {
            get {
                return ResourceManager.GetString("MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Movement Alarm.
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Movement Alarm (100 mts).
        /// </summary>
        internal static string Movement100 {
            get {
                return ResourceManager.GetString("Movement100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Movement Alarm (200 mts).
        /// </summary>
        internal static string Movement200 {
            get {
                return ResourceManager.GetString("Movement200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Movement Alarm (50 mts).
        /// </summary>
        internal static string Movement50 {
            get {
                return ResourceManager.GetString("Movement50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Movement Alarm.
        /// </summary>
        internal static string MovementOff {
            get {
                return ResourceManager.GetString("MovementOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is not set.
        /// </summary>
        internal static string PhoneNumberMissing {
            get {
                return ResourceManager.GetString("PhoneNumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Device.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string ResetApp {
            get {
                return ResourceManager.GetString("ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePlaceholder {
            get {
                return ResourceManager.GetString("SavePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string SenderMenu {
            get {
                return ResourceManager.GetString("SenderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending SMS.
        /// </summary>
        internal static string SmsError {
            get {
                return ResourceManager.GetString("SmsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS not supported on this device.
        /// </summary>
        internal static string SmsNotSupported {
            get {
                return ResourceManager.GetString("SmsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the Device.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit has been added..
        /// </summary>
        internal static string UnitAdded {
            get {
                return ResourceManager.GetString("UnitAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit settings have been saved..
        /// </summary>
        internal static string UnitSaved {
            get {
                return ResourceManager.GetString("UnitSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
